# Generated by Django 5.2.15 on 2026-06-14 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Название продукта", max_length=200),
                ),
                ("description", models.TextField(help_text="Описание продукта")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Цена продукта", max_digits=10
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Количество на складе"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата создания продукта"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, help_text="Наличие продукта в продаже"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Заметки к заказу")),
                (
                    "customer_address",
                    models.CharField(help_text="Адрес покупателя", max_length=300),
                ),
                (
                    "order_date",
                    models.DateTimeField(auto_now_add=True, help_text="Дата заказа"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, сделавший заказ",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, help_text="Продукты в заказе", to="shopapp.product"
                    ),
                ),
            ],
        ),
    ]
