# Generated by Django 5.2.15 on 2026-06-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0001_product_migration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
