# Generated by Django 5.2.15 on 2026-06-14 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0002_product_only"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Заметки к заказу")),
                (
                    "customer_address",
                    models.CharField(help_text="Адрес покупателя", max_length=300),
                ),
                (
                    "order_date",
                    models.DateTimeField(auto_now_add=True, help_text="Дата заказа"),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, help_text="Продукты в заказе", to="shopapp.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, сделавший заказ",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
