# Generated by Django 5.2.15 on 2026-06-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0003_order_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Скидка в процентах",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(
                default=True, help_text="Наличие продукта в продаже (архив)"
            ),
        ),
    ]
