# Generated by Django 5.2.15 on 2026-07-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0006_product_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
